=== gabrielionescu/testRepos/europass.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="europass">
        <xs:complexType>
            <xs:sequence>
                <!-- personal information -->
                <xs:element name="personalInformation">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- name -->
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="firstname" type="xs:string" />
                                        <xs:element name="surname"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <!-- end name  == begin adress-->
                            <xs:element name="Adress">
                                <xs:complexType>
                                    <xs:sequence>
                                        <!-- street and number -->
                                        <xs:sequence>
                                            <xs:element name="street"/>
                                            <xs:element name="number"/>
                                        </xs:sequence>
                                        <xs:element name="postalCode"/>
                                        <xs:element name="city"/>
                                        <!-- thi will be selected from a dropdown list -->
                                        <xs:element name="country"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <!-- end adress -->
                            <!-- telephone -->
                            <xs:element name="telephone">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="type"/>
                                        <xs:element name="telNumber"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="email"/>
                            <xs:element name="website"/>
                            <xs:element name="instantMessaging">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="provider"/>
                                        <xs:element name="IMusername"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="extraFields">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="sex">
                                         
                                        </xs:element>
                                        <xs:element name="dateOfBirth">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="day"/>
                                                  <xs:element name="month"/>
                                                  <xs:element name="year"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="nationality"/>

                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>


            <xs:attribute name="orderid" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== gabrielionescu/testRepos/StudentEuropass.xml
<?xml-stylesheet type="text/css" href="file:/home/gabriel/Desktop/europass/europass/europass.css"?>

<europass orderid="889923" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/home/gabriel/Desktop/europass/europass/europass.xsd">
    <personalInformation>
        <name>
            <firstname>Livaina</firstname>
            <surname/>
        </name>
        <Adress>
            <street>Sta</street>
            <number>21</number>
            <postalCode>sdad</postalCode>
            <city>adsa</city>
            <country>ada</country>
        </Adress>
        <telephone>
            <type attribute="Home"/>
            <telNumber>0745554125</telNumber>
        </telephone>
        
        <email/>
        <website/>
        <instantMessaging>
            <provider attribute="Skype"/>
            <IMusername/>
        </instantMessaging>
        <extraFields>
            <sex>Male</sex>
            <dateOfBirth>
                <day/>
                <month/>
                <year/>
            </dateOfBirth>
            <nationality/>
        </extraFields>
    </personalInformation>
    
</europass>
